# Deploy a Flutter Web App to Firebase Hosting on merge

name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable' # Or 'beta', 'dev', 'master'

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web App
        run: flutter build web --release # This command creates the 'build/web' directory

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DRONEWORKZ_FACC9 }}'
          channelId: live
          projectId: droneworkz-facc9
